server:
  port: ${PORT:8080}
  shutdown: graceful

logging:
  level[net.talaatharb]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  application:
    name: couchbase-demo
  lifecycle:
    timeout-per-shutdown-phase: 30s
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  couchbase:
    connection-string: couchbase://127.0.0.1
    username: admin
    password: password

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true